travis:
  secure:
    BINSTAR_TOKEN: UDHXFh6AncGcCcjlnyQMKJf0XJ/Z3fWtWfAowC/pKCE6ZIQhOPp3OF7+Ra3zeJvbuFUtt1n74i5OWAH9YKyZ6cEVAJ5HgSKYgq3CEr7g9ZjEx9jD7Hk91rKlmxcGtckLP33a+6q40LCCAJnMiTHnFSzUI8VBeXAMXeZ/+6+BlVR0D5jl30kk7dXATPiHeD/A09w6AaC9EO2zOkF2qxypS6uwYgX3UIVOqHbOHOINROBqnSk7vlSdo9LOm5P2i+CH6rUuYrG3sGiKZsSqT9L9rXnVXm9SexnZFHsVPq+DZfJ5ZB7D4RD8DS2u1HEXIH0kD+OZgeZpHD7gmZNnQ1/lW8f8Vc5jbuGx6Q9wBwvjinrkWEIvJzzm+CwJfpob9sKoxRtFyilXKiGWvnS+2ZBptBOm0/RpA2+myQ27BQxHsjA7ejH09o+BdtSqLK59edc6IWgBMB99nt4nhpOf7+sEnd4Wv0f9kUIjBpLWlbnYNznNDQnMeefqesGklDkYqnz9LpVIfCzJIwFYjmv5fAwgqccGE8UT5C0jNCaruCJ4mP6k1fZQMZrNnCJwqg6pQGBRl8V5TAGsIiquGkHCvxJ3dTYDg0Y1BukSpO/12E6b48rnW9OpQM6i45oikX71hkIGKgxvNWgo9iVPuvYwk5IzCNmhz813sOffeGxmnTzpvDQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
